//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bridge$0 from "../../../../wzhejunqiu/ds-code/desktop/bridge/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "agent:event": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = bridge$0.AgentEventEnvelope.createFrom;

configure();
