// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatMessage is a history row for resume rendering.
 */
export interface ChatMessage {
    "id": number;
    "role": string;
    "content": string;
    "reasoning"?: string;
    "toolCalls"?: string;
    "toolCallId"?: string;
    "toolName"?: string;
    "createdAt": number;
}

/**
 * ChatSummary is an Agent conversation window row.
 */
export interface ChatSummary {
    "id": string;
    "title": string;
    "model": string;
    "updatedAt": number;
    "createdAt": number;
}

/**
 * Summary is a workspace row for UI listing.
 */
export interface Summary {
    "id": string;
    "name": string;
    "root": string;
    "active": boolean;
    "lastOpenedAt": number;
    "valid": boolean;
}

/**
 * WindowLayout persists column widths and collapse state.
 */
export interface WindowLayout {
    "width"?: number;
    "height"?: number;
    "leftWidth"?: number;
    "rightWidth"?: number;
    "leftCollapsed"?: boolean;
    "rightCollapsed"?: boolean;
}
