// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../cmd/ds-code/app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../internal/config/models.js";

/**
 * ChatMessage is a history row for resume rendering.
 */
export interface ChatMessage {
    "id": number;
    "role": string;
    "content": string;
    "contentFormat"?: string;
    "reasoning"?: string;
    "toolCalls"?: string;
    "toolCallId"?: string;
    "toolName"?: string;
    "createdAt": number;
}

/**
 * ChatSummary is an Agent conversation window row.
 */
export interface ChatSummary {
    "id": string;
    "title": string;
    "model": string;
    "runMode"?: string;
    "updatedAt": number;
    "createdAt": number;
}

/**
 * MCPLSPConfigView is editable MCP/LSP config.
 */
export interface MCPLSPConfigView {
    "mcp": config$0.MCPConfig;
    "lsp": config$0.LSPConfig;
}

/**
 * ServiceStatusView is re-exported for Wails bindings.
 */
export type ServiceStatusView = app$0.ServiceStatusView;

/**
 * SessionUsageView is cumulative token usage and cost for the status bar.
 */
export interface SessionUsageView {
    "model": string;
    "promptTokens": number;
    "completionTokens": number;
    "estimatedCostCNY": number;
    "estimatedCostLabel": string;
}

/**
 * SlashResult is returned when a slash command is handled.
 */
export interface SlashResult {
    "output": string;
    "newSessionId"?: string;
    "handled": boolean;
}

/**
 * Summary is a workspace row for UI listing.
 */
export interface Summary {
    "id": string;
    "name": string;
    "root": string;
    "active": boolean;
    "lastOpenedAt": number;
    "valid": boolean;
}

/**
 * WindowLayout persists column widths and collapse state.
 */
export interface WindowLayout {
    "width"?: number;
    "height"?: number;
    "leftWidth"?: number;
    "rightWidth"?: number;
    "leftCollapsed"?: boolean;
    "rightCollapsed"?: boolean;
}
