// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopService exposes Wails bindings for the M0 single-workspace PoC.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * CancelTurn cancels the in-flight turn.
 */
export function CancelTurn(): $CancellablePromise<void> {
    return $Call.ByID(2246300016);
}

/**
 * OpenProject binds a single workspace/project root and prepares the agent runner.
 */
export function OpenProject(root: string): $CancellablePromise<void> {
    return $Call.ByID(1074195746, root);
}

/**
 * ProjectRoot returns the active project root (for UI status).
 */
export function ProjectRoot(): $CancellablePromise<string> {
    return $Call.ByID(956207050);
}

/**
 * ResolvePermission completes an inline approval card.
 */
export function ResolvePermission(requestID: string, allow: boolean): $CancellablePromise<void> {
    return $Call.ByID(1546399332, requestID, allow);
}

/**
 * SendMessage starts a new agent turn asynchronously.
 */
export function SendMessage(text: string): $CancellablePromise<void> {
    return $Call.ByID(2661530478, text);
}
