// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopService exposes Wails bindings for the desktop MVP.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspace$0 from "../../desktop/workspace/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * APIKeyStatus reports whether an API key is configured via environment.
 */
export function APIKeyStatus(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(3416869600);
}

/**
 * ActiveWorkspaceID returns the active workspace id.
 */
export function ActiveWorkspaceID(): $CancellablePromise<string> {
    return $Call.ByID(1573211129);
}

/**
 * AddWorkspace adds a project root as a workspace.
 */
export function AddWorkspace(root: string): $CancellablePromise<workspace$0.Summary> {
    return $Call.ByID(3339324385, root);
}

/**
 * CancelTurn cancels the in-flight turn for a workspace.
 */
export function CancelTurn(wsID: string): $CancellablePromise<void> {
    return $Call.ByID(2246300016, wsID);
}

/**
 * Close releases all workspace resources.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(4084862627);
}

/**
 * CreateChat creates a new agent conversation in a workspace.
 */
export function CreateChat(wsID: string): $CancellablePromise<workspace$0.ChatSummary> {
    return $Call.ByID(309053043, wsID);
}

/**
 * GetConfig returns user-level or project-level config for a workspace.
 * scope: "user" or "project" (requires wsID for project).
 */
export function GetConfig(scope: string, wsID: string): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(3281232725, scope, wsID);
}

/**
 * GetWindowLayout returns persisted column layout.
 */
export function GetWindowLayout(): $CancellablePromise<workspace$0.WindowLayout> {
    return $Call.ByID(3099839837);
}

/**
 * ListChats lists agent conversation windows for a workspace.
 */
export function ListChats(wsID: string): $CancellablePromise<workspace$0.ChatSummary[] | null> {
    return $Call.ByID(2087797316, wsID);
}

/**
 * ListWorkspaces returns all registered workspaces.
 */
export function ListWorkspaces(): $CancellablePromise<workspace$0.Summary[] | null> {
    return $Call.ByID(94092003);
}

/**
 * OpenProject adds a workspace (compat with M0 CLI arg).
 */
export function OpenProject(root: string): $CancellablePromise<void> {
    return $Call.ByID(1074195746, root);
}

/**
 * PickFolder opens a native folder picker (macOS); implemented in pick_darwin.go.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(271684348);
}

/**
 * ProjectRoot returns the active workspace project root.
 */
export function ProjectRoot(): $CancellablePromise<string> {
    return $Call.ByID(956207050);
}

/**
 * RemoveWorkspace removes a workspace from the registry.
 */
export function RemoveWorkspace(id: string): $CancellablePromise<void> {
    return $Call.ByID(4020859070, id);
}

/**
 * RenameChat renames a session.
 */
export function RenameChat(wsID: string, sessionID: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(3009056173, wsID, sessionID, title);
}

/**
 * ResolvePermission completes an inline approval card.
 * choice: "allow"|"deny" for write_shell; "allow_once"|"allow_always"|"deny" for web_fetch.
 */
export function ResolvePermission(wsID: string, requestID: string, choice: string): $CancellablePromise<void> {
    return $Call.ByID(1546399332, wsID, requestID, choice);
}

/**
 * ResumeChat loads session history.
 */
export function ResumeChat(wsID: string, sessionID: string): $CancellablePromise<[workspace$0.ChatMessage[] | null, workspace$0.ChatSummary]> {
    return $Call.ByID(2237051732, wsID, sessionID);
}

/**
 * SaveConfigPatch updates permission mode for user or project scope.
 */
export function SaveConfigPatch(scope: string, wsID: string, permissionMode: string): $CancellablePromise<void> {
    return $Call.ByID(1912498780, scope, wsID, permissionMode);
}

/**
 * SaveWindowLayout persists column layout.
 */
export function SaveWindowLayout(layout: workspace$0.WindowLayout): $CancellablePromise<void> {
    return $Call.ByID(4094329466, layout);
}

/**
 * SendMessage starts an agent turn.
 */
export function SendMessage(wsID: string, sessionID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(2661530478, wsID, sessionID, text);
}

/**
 * SwitchWorkspace sets the active workspace.
 */
export function SwitchWorkspace(id: string): $CancellablePromise<void> {
    return $Call.ByID(1767647762, id);
}

/**
 * TurnStatus returns idle/running/waiting_permission for a workspace.
 */
export function TurnStatus(wsID: string): $CancellablePromise<string> {
    return $Call.ByID(2751455620, wsID);
}
