// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopService exposes Wails bindings for the desktop MVP.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as inspect$0 from "../../desktop/inspect/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sys$0 from "../../desktop/sys/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspace$0 from "../../desktop/workspace/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * APIKeyStatus reports whether an API key is configured via environment.
 */
export function APIKeyStatus(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(3416869600);
}

/**
 * ActiveWorkspaceID returns the active workspace id.
 */
export function ActiveWorkspaceID(): $CancellablePromise<string> {
    return $Call.ByID(1573211129);
}

/**
 * AddWorkspace adds a project root as a workspace.
 */
export function AddWorkspace(root: string): $CancellablePromise<workspace$0.Summary> {
    return $Call.ByID(3339324385, root).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CancelTurn cancels the in-flight turn for a workspace.
 */
export function CancelTurn(wsID: string): $CancellablePromise<void> {
    return $Call.ByID(2246300016, wsID);
}

/**
 * CheckDependencies reports git/node/gopls availability.
 */
export function CheckDependencies(): $CancellablePromise<sys$0.DepStatus[]> {
    return $Call.ByID(2285041026).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Close releases all workspace resources.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(4084862627);
}

/**
 * CreateChat creates a new agent conversation in a workspace.
 */
export function CreateChat(wsID: string): $CancellablePromise<workspace$0.ChatSummary> {
    return $Call.ByID(309053043, wsID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ExecuteSlash runs a slash command without starting a turn.
 */
export function ExecuteSlash(wsID: string, sessionID: string, line: string): $CancellablePromise<workspace$0.SlashResult> {
    return $Call.ByID(100156161, wsID, sessionID, line).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetConfig returns user-level or project-level config for a workspace.
 * scope: "user" or "project" (requires wsID for project).
 */
export function GetConfig(scope: string, wsID: string): $CancellablePromise<$models.ConfigView> {
    return $Call.ByID(3281232725, scope, wsID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetWindowLayout returns persisted column layout.
 */
export function GetWindowLayout(): $CancellablePromise<workspace$0.WindowLayout> {
    return $Call.ByID(3099839837).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListChats lists agent conversation windows for a workspace.
 */
export function ListChats(wsID: string): $CancellablePromise<workspace$0.ChatSummary[]> {
    return $Call.ByID(2087797316, wsID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListWorkspaces returns all registered workspaces.
 */
export function ListWorkspaces(): $CancellablePromise<workspace$0.Summary[]> {
    return $Call.ByID(94092003).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * OpenProject adds a workspace (compat with M0 CLI arg).
 */
export function OpenProject(root: string): $CancellablePromise<void> {
    return $Call.ByID(1074195746, root);
}

/**
 * PickFolder opens a native folder picker (macOS); implemented in pick_darwin.go.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(271684348);
}

/**
 * PreviewPatch returns Monaco-ready diffs for apply_patch text.
 */
export function PreviewPatch(wsID: string, patchText: string): $CancellablePromise<inspect$0.PatchFileDiff[]> {
    return $Call.ByID(1732033947, wsID, patchText).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ProjectRoot returns the active workspace project root.
 */
export function ProjectRoot(): $CancellablePromise<string> {
    return $Call.ByID(956207050);
}

/**
 * ReadFilePreview returns read-only file content for Inspector.
 */
export function ReadFilePreview(wsID: string, path: string, offset: number, limit: number): $CancellablePromise<inspect$0.FilePreviewResult> {
    return $Call.ByID(191215701, wsID, path, offset, limit).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * RemoveWorkspace removes a workspace from the registry.
 */
export function RemoveWorkspace(id: string): $CancellablePromise<void> {
    return $Call.ByID(4020859070, id);
}

/**
 * RenameChat renames a session.
 */
export function RenameChat(wsID: string, sessionID: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(3009056173, wsID, sessionID, title);
}

/**
 * ResolvePermission completes an inline approval card.
 */
export function ResolvePermission(wsID: string, requestID: string, choice: string): $CancellablePromise<void> {
    return $Call.ByID(1546399332, wsID, requestID, choice);
}

/**
 * ResumeChat loads session history.
 */
export function ResumeChat(wsID: string, sessionID: string): $CancellablePromise<[workspace$0.ChatMessage[], workspace$0.ChatSummary]> {
    return $Call.ByID(2237051732, wsID, sessionID).then(($result: any) => {
        $result[0] = $$createType13($result[0]);
        $result[1] = $$createType3($result[1]);
        return $result;
    });
}

/**
 * SaveConfigPatch updates permission mode for user or project scope.
 */
export function SaveConfigPatch(scope: string, wsID: string, permissionMode: string): $CancellablePromise<void> {
    return $Call.ByID(1912498780, scope, wsID, permissionMode);
}

/**
 * SaveWindowLayout persists column layout.
 */
export function SaveWindowLayout(layout: workspace$0.WindowLayout): $CancellablePromise<void> {
    return $Call.ByID(4094329466, layout);
}

/**
 * SendMessage starts an agent turn or handles a slash command.
 */
export function SendMessage(wsID: string, sessionID: string, text: string): $CancellablePromise<workspace$0.SlashResult> {
    return $Call.ByID(2661530478, wsID, sessionID, text).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SessionRunMode returns the run mode for a session.
 */
export function SessionRunMode(wsID: string, sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(3852721379, wsID, sessionID);
}

/**
 * SetRunMode switches agent/plan mode for a session.
 */
export function SetRunMode(wsID: string, sessionID: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(2358595175, wsID, sessionID, mode);
}

/**
 * SwitchWorkspace sets the active workspace.
 */
export function SwitchWorkspace(id: string): $CancellablePromise<void> {
    return $Call.ByID(1767647762, id);
}

/**
 * TurnStatus returns idle/running/waiting_permission for a workspace.
 */
export function TurnStatus(wsID: string): $CancellablePromise<string> {
    return $Call.ByID(2751455620, wsID);
}

// Private type creation functions
const $$createType0 = workspace$0.Summary.createFrom;
const $$createType1 = sys$0.DepStatus.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = workspace$0.ChatSummary.createFrom;
const $$createType4 = workspace$0.SlashResult.createFrom;
const $$createType5 = $models.ConfigView.createFrom;
const $$createType6 = workspace$0.WindowLayout.createFrom;
const $$createType7 = $Create.Array($$createType3);
const $$createType8 = $Create.Array($$createType0);
const $$createType9 = inspect$0.PatchFileDiff.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = inspect$0.FilePreviewResult.createFrom;
const $$createType12 = workspace$0.ChatMessage.createFrom;
const $$createType13 = $Create.Array($$createType12);
