// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConfigView is a read-only config snapshot for the settings UI.
 */
export class ConfigView {
    "permissionMode": string;
    "model": string;
    "runMode": string;
    "projectRoot"?: string;

    /** Creates a new ConfigView instance. */
    constructor($$source: Partial<ConfigView> = {}) {
        if (!("permissionMode" in $$source)) {
            this["permissionMode"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("runMode" in $$source)) {
            this["runMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigView instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigView($$parsedSource as Partial<ConfigView>);
    }
}
