// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConfigView is a read-only config snapshot for the settings UI.
 */
export class ConfigView {
    "permissionMode": string;
    "model": string;
    "reasoningEffort": string;
    "runMode": string;
    "assistantOutputFormat": string;
    "tracingEnabled": boolean;
    "tracingExporter": string;
    "tracingOtlpEndpoint": string;
    "projectRoot"?: string;

    /** Creates a new ConfigView instance. */
    constructor($$source: Partial<ConfigView> = {}) {
        if (!("permissionMode" in $$source)) {
            this["permissionMode"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("reasoningEffort" in $$source)) {
            this["reasoningEffort"] = "";
        }
        if (!("runMode" in $$source)) {
            this["runMode"] = "";
        }
        if (!("assistantOutputFormat" in $$source)) {
            this["assistantOutputFormat"] = "";
        }
        if (!("tracingEnabled" in $$source)) {
            this["tracingEnabled"] = false;
        }
        if (!("tracingExporter" in $$source)) {
            this["tracingExporter"] = "";
        }
        if (!("tracingOtlpEndpoint" in $$source)) {
            this["tracingOtlpEndpoint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigView instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigView($$parsedSource as Partial<ConfigView>);
    }
}

/**
 * SettingsPatch is a partial settings update from the desktop UI.
 */
export class SettingsPatch {
    "permissionMode"?: string;
    "model"?: string;
    "reasoningEffort"?: string;
    "tracingEnabled"?: boolean | null;
    "tracingExporter"?: string;
    "tracingOtlpEndpoint"?: string;

    /** Creates a new SettingsPatch instance. */
    constructor($$source: Partial<SettingsPatch> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsPatch instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsPatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsPatch($$parsedSource as Partial<SettingsPatch>);
    }
}
