// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigView is a read-only config snapshot for the settings UI.
 */
export interface ConfigView {
    "permissionMode": string;
    "model": string;
    "runMode": string;
    "assistantOutputFormat": string;
    "projectRoot"?: string;
}
