// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";

/**
 * AgentEventEnvelope is the versioned event wrapper sent over Wails Events.
 */
export interface AgentEventEnvelope {
    "v": number;
    "seq": number;
    "turnId": string;
    "streamId": string;
    "workspaceId": string;
    "kind": AgentEventKind;
    "ts": number;
    "critical": boolean;
    "payload": json$0.RawMessage;
}

/**
 * AgentEventKind identifies the event payload shape.
 */
export enum AgentEventKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindTurnStarted = "turn.started",
    KindContentDelta = "content.delta",
    KindReasoningDelta = "reasoning.delta",
    KindToolStart = "tool.start",
    KindToolEnd = "tool.end",
    KindAssistantSegmentEnd = "assistant.segment_end",
    KindPlanningStart = "planning.start",
    KindPlanningEnd = "planning.end",
    KindSubagentStart = "subagent.start",
    KindSubagentEnd = "subagent.end",
    KindSubagentToolStart = "subagent.tool.start",
    KindSubagentToolEnd = "subagent.tool.end",
    KindUsageUpdate = "usage.update",
    KindTurnDone = "turn.done",
    KindPermissionRequest = "permission.request",
};
