// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export interface LSPConfig {
    "Enabled": boolean;
    "IdleShutdown": time$0.Duration;
    "DiagnosticsTimeout": time$0.Duration;
    "MaxFilesPerCall": number;
    "MaxIssuesPerFile": number;
    "WarmupOnStart": string[] | null;
    "Servers": { [_ in string]?: LSPServerConfig } | null;
}

export interface LSPServerConfig {
    "Command": string;
    "Args": string[] | null;
    "Extensions": string[] | null;
    "Env": { [_ in string]?: string } | null;
    "Disabled": boolean;
}

export interface MCPConfig {
    "Servers": MCPServerConfig[] | null;
}

export interface MCPServerConfig {
    "Name": string;
    "Command": string;
    "Args": string[] | null;
    "Env": { [_ in string]?: string } | null;
}
