// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Meta is a checkpoint list row for the UI.
 */
export interface Meta {
    "id": number;
    "tool": string;
    "files": string[] | null;
    "createdAt": number;
}
