// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Meta is a checkpoint list row for the UI.
 */
export class Meta {
    "id": number;
    "tool": string;
    "files": string[];
    "createdAt": number;

    /** Creates a new Meta instance. */
    constructor($$source: Partial<Meta> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Meta instance from a string or object.
     */
    static createFrom($$source: any = {}): Meta {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField2_0($$parsedSource["files"]);
        }
        return new Meta($$parsedSource as Partial<Meta>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
