// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DepStatus reports whether a dependency binary is available.
 */
export interface DepStatus {
    "name": string;
    "found": boolean;
    "path"?: string;
    "hint"?: string;
}
