// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DepStatus reports whether a dependency binary is available.
 */
export class DepStatus {
    "name": string;
    "found": boolean;
    "path"?: string;
    "hint"?: string;

    /** Creates a new DepStatus instance. */
    constructor($$source: Partial<DepStatus> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DepStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DepStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DepStatus($$parsedSource as Partial<DepStatus>);
    }
}
