// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LSPServerStatusView is one LSP server row for the desktop settings UI.
 */
export class LSPServerStatusView {
    "id": string;
    "command": string;
    "disabled": boolean;
    "commandFound": boolean;
    "started": boolean;
    "hint"?: string;

    /** Creates a new LSPServerStatusView instance. */
    constructor($$source: Partial<LSPServerStatusView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = false;
        }
        if (!("commandFound" in $$source)) {
            this["commandFound"] = false;
        }
        if (!("started" in $$source)) {
            this["started"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LSPServerStatusView instance from a string or object.
     */
    static createFrom($$source: any = {}): LSPServerStatusView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LSPServerStatusView($$parsedSource as Partial<LSPServerStatusView>);
    }
}

/**
 * LSPStatusView summarizes LSP configuration and runtime state.
 */
export class LSPStatusView {
    "enabled": boolean;
    "servers": LSPServerStatusView[];

    /** Creates a new LSPStatusView instance. */
    constructor($$source: Partial<LSPStatusView> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("servers" in $$source)) {
            this["servers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LSPStatusView instance from a string or object.
     */
    static createFrom($$source: any = {}): LSPStatusView {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField1_0($$parsedSource["servers"]);
        }
        return new LSPStatusView($$parsedSource as Partial<LSPStatusView>);
    }
}

/**
 * MCPServerStatusView is one MCP server row for the desktop settings UI.
 */
export class MCPServerStatusView {
    "name": string;
    "command": string;
    "connected": boolean;
    "registeredTools": number;
    "discoveredTools": number;

    /** Creates a new MCPServerStatusView instance. */
    constructor($$source: Partial<MCPServerStatusView> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("registeredTools" in $$source)) {
            this["registeredTools"] = 0;
        }
        if (!("discoveredTools" in $$source)) {
            this["discoveredTools"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPServerStatusView instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPServerStatusView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPServerStatusView($$parsedSource as Partial<MCPServerStatusView>);
    }
}

/**
 * MCPSkippedToolView is a skipped MCP tool row.
 */
export class MCPSkippedToolView {
    "server": string;
    "tool": string;
    "reason": string;

    /** Creates a new MCPSkippedToolView instance. */
    constructor($$source: Partial<MCPSkippedToolView> = {}) {
        if (!("server" in $$source)) {
            this["server"] = "";
        }
        if (!("tool" in $$source)) {
            this["tool"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPSkippedToolView instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPSkippedToolView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPSkippedToolView($$parsedSource as Partial<MCPSkippedToolView>);
    }
}

/**
 * MCPStatusView summarizes MCP configuration and runtime state.
 */
export class MCPStatusView {
    "configuredServers": MCPServerStatusView[];
    "skippedTools": MCPSkippedToolView[];
    "connected": boolean;

    /** Creates a new MCPStatusView instance. */
    constructor($$source: Partial<MCPStatusView> = {}) {
        if (!("configuredServers" in $$source)) {
            this["configuredServers"] = [];
        }
        if (!("skippedTools" in $$source)) {
            this["skippedTools"] = [];
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPStatusView instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPStatusView {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("configuredServers" in $$parsedSource) {
            $$parsedSource["configuredServers"] = $$createField0_0($$parsedSource["configuredServers"]);
        }
        if ("skippedTools" in $$parsedSource) {
            $$parsedSource["skippedTools"] = $$createField1_0($$parsedSource["skippedTools"]);
        }
        return new MCPStatusView($$parsedSource as Partial<MCPStatusView>);
    }
}

/**
 * ServiceStatusView combines MCP and LSP status for Inspector overview.
 */
export class ServiceStatusView {
    "mcp": MCPStatusView;
    "lsp": LSPStatusView;

    /** Creates a new ServiceStatusView instance. */
    constructor($$source: Partial<ServiceStatusView> = {}) {
        if (!("mcp" in $$source)) {
            this["mcp"] = (new MCPStatusView());
        }
        if (!("lsp" in $$source)) {
            this["lsp"] = (new LSPStatusView());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceStatusView instance from a string or object.
     */
    static createFrom($$source: any = {}): ServiceStatusView {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mcp" in $$parsedSource) {
            $$parsedSource["mcp"] = $$createField0_0($$parsedSource["mcp"]);
        }
        if ("lsp" in $$parsedSource) {
            $$parsedSource["lsp"] = $$createField1_0($$parsedSource["lsp"]);
        }
        return new ServiceStatusView($$parsedSource as Partial<ServiceStatusView>);
    }
}

// Private type creation functions
const $$createType0 = LSPServerStatusView.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = MCPServerStatusView.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = MCPSkippedToolView.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = MCPStatusView.createFrom;
const $$createType7 = LSPStatusView.createFrom;
