// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LSPServerStatusView is one LSP server row for the desktop settings UI.
 */
export interface LSPServerStatusView {
    "id": string;
    "command": string;
    "disabled": boolean;
    "commandFound": boolean;
    "started": boolean;
    "hint"?: string;
}

/**
 * LSPStatusView summarizes LSP configuration and runtime state.
 */
export interface LSPStatusView {
    "enabled": boolean;
    "servers": LSPServerStatusView[] | null;
}

/**
 * MCPServerStatusView is one MCP server row for the desktop settings UI.
 */
export interface MCPServerStatusView {
    "name": string;
    "command": string;
    "connected": boolean;
    "registeredTools": number;
    "discoveredTools": number;
}

/**
 * MCPSkippedToolView is a skipped MCP tool row.
 */
export interface MCPSkippedToolView {
    "server": string;
    "tool": string;
    "reason": string;
}

/**
 * MCPStatusView summarizes MCP configuration and runtime state.
 */
export interface MCPStatusView {
    "configuredServers": MCPServerStatusView[] | null;
    "skippedTools": MCPSkippedToolView[] | null;
    "connected": boolean;
}

/**
 * ServiceStatusView combines MCP and LSP status for Inspector overview.
 */
export interface ServiceStatusView {
    "mcp": MCPStatusView;
    "lsp": LSPStatusView;
}
