// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FilePreviewResult is a read-only file slice for Inspector.
 */
export class FilePreviewResult {
    "path": string;
    "content": string;
    "language": string;

    /** Creates a new FilePreviewResult instance. */
    constructor($$source: Partial<FilePreviewResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilePreviewResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FilePreviewResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilePreviewResult($$parsedSource as Partial<FilePreviewResult>);
    }
}

/**
 * PatchFileDiff is one file's before/after preview for Monaco diff.
 */
export class PatchFileDiff {
    "path": string;
    "original": string;
    "modified": string;
    "language": string;

    /** Creates a new PatchFileDiff instance. */
    constructor($$source: Partial<PatchFileDiff> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("original" in $$source)) {
            this["original"] = "";
        }
        if (!("modified" in $$source)) {
            this["modified"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PatchFileDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): PatchFileDiff {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PatchFileDiff($$parsedSource as Partial<PatchFileDiff>);
    }
}
