// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FilePreviewResult is a read-only file slice for Inspector.
 */
export interface FilePreviewResult {
    "path": string;
    "content": string;
    "language": string;
}

/**
 * PatchFileDiff is one file's before/after preview for Monaco diff.
 */
export interface PatchFileDiff {
    "path": string;
    "original": string;
    "modified": string;
    "language": string;
}
